import {Engine,Scene,ArcRotateCamera,Vector3,HemisphericLight,DirectionalLight,ShadowGenerator,SceneInstrumentation} from '@babylonjs/core';
import {createParkEnvironment} from '../src/babylon/ParkEnvironment';
import {loadModel} from '../src/babylon/ModelLoader';
import {batchStaticSunShadows} from '../src/babylon/ShadowCasterBatch';
const out=document.querySelector('#result')!;
const engine=new Engine(document.querySelector('#scene') as HTMLCanvasElement,true,{preserveDrawingBuffer:true});const scene=new Scene(engine);engine.disableUniformBuffers=true;
const camera=new ArcRotateCamera('camera',-Math.PI/2,.7,25,Vector3.Zero(),scene);new HemisphericLight('ambient',Vector3.Up(),scene).intensity=.5;
const sun=new DirectionalLight('sun',new Vector3(-1,-2,1).normalize(),scene);sun.position=sun.direction.scale(-50);sun.intensity=.8;
const inst=new SceneInstrumentation(scene);inst.captureFrameTime=true;
const settle=async()=>{for(let i=0;i<12;i++){scene.render();await new Promise(r=>setTimeout(r,20))}};
const capture=async()=>{await settle();return {pixels:await engine.readPixels(0,0,960,720),drawCalls:engine._drawCalls.current}};
const diff=(a,b)=>{let differing=0,max=0,sum=0,over2=0,over8=0;for(let i=0;i<a.length;i++){const d=Math.abs(a[i]-b[i]);if(d)differing++;if(d>2)over2++;if(d>8)over8++;max=Math.max(max,d);sum+=d}return {differing,max,over2,over8,mean:sum/a.length}};
try{const blob=await (await fetch(new URLSearchParams(location.search).get('model') ?? '../.qa/v89.glb')).blob();const model=await loadModel(scene,blob,undefined,{showTextures:true,edgeRendering:false});createParkEnvironment(scene,model.center,model.size);camera.target.copyFrom(model.center);camera.radius=model.diagonal*1.1;sun.shadowFrustumSize=model.diagonal*1.5;sun.shadowMinZ=.1;sun.shadowMaxZ=200;sun.autoCalcShadowZBounds=true;
const sg=new ShadowGenerator(1024,sun);sg.usePercentageCloserFiltering=true;sg.filteringQuality=ShadowGenerator.QUALITY_MEDIUM;sg.bias=.001;sg.normalBias=.02;model.shadowCasters.forEach(m=>sg.addShadowCaster(m,false));
const target=(scene as any)._transmissionHelper.getOpaqueTarget();const culling=target.getCustomRenderList;target.getCustomRenderList=null;const results=[];for(const [alpha,beta]of [[-Math.PI/2,.3],[-.8,1.1],[1.1,.8]]){camera.alpha=alpha;camera.beta=beta;const before=await capture();const control=await capture();const dispose=batchStaticSunShadows(sg);target.getCustomRenderList=culling;const after=await capture();if(alpha===1.1){const row=document.createElement('div');row.style.display='flex';for(const data of [control.pixels,after.pixels,Uint8Array.from(after.pixels,(v,i)=>i%4===3?255:Math.min(255,Math.abs(v-control.pixels[i])*5))]){const c=document.createElement('canvas');c.width=960;c.height=720;c.style.width='400px';c.style.height='300px';const ctx=c.getContext('2d')!;const image=ctx.createImageData(960,720);for(let y=0;y<720;y++)image.data.set(data.subarray((719-y)*960*4,(720-y)*960*4),y*960*4);ctx.putImageData(image,0,0);row.append(c)}document.body.prepend(row);(document.querySelector('#scene') as HTMLElement).style.display='none'}results.push({before:before.drawCalls,after:after.drawCalls,control:diff(before.pixels,control.pixels),difference:diff(control.pixels,after.pixels),casters:sg.getShadowMap()?.renderList?.length});dispose?.();target.getCustomRenderList=null;}
if(results.some(r=>r.control.differing||r.difference.differing||r.after>=r.before))throw new Error('Render comparison failed: '+JSON.stringify(results));out.textContent='PASS: pixel-identical in all three views\n'+JSON.stringify(results,null,2);document.title='PASS render performance';}catch(e){out.textContent=String(e);document.title='FAIL shadow batch'}
